python ./main.py \
    --learning_rate 0.001 \
    --discount_factor 0.99 \
    --env_name LunarLander-v2 \
    --iterations 1000 \
    --episodes 100 \
    --use_ddqn false \
    --batch_size 128 \
    --n_threads 1 \